- name: Disable default available redis and enable version 7
  ansible.builtin.shell:
    cmd: dnf module disable redis -y; dnf module enable redis:7 -y

- name: Install Redis:7 version
  ansible.builtin.dnf:
    name: redis
    state: present

- name: Update default listening port
  ansible.builtin.replace:
    path: /etc/redis.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: Enable and start app service
  ansible.builtin.systemd_service:
    name: redis
    enabled: true
    state: started