- name: Install python3
  ansible.builtin.dnf:
    name: python3 gcc python3-devel
    state: present

- name: Invoke App pre setup role
  ansible.builtin.include_tasks:
    file: app_pre_setup.yml

- name: Navigate app directory and run npm Install
  ansible.builtin.command:
    cmd: pip3 install -r requirements.txt
    chdir: /app

- name: Invoke App pre setup role
  ansible.builtin.include_tasks:
    file: systemd_service.yml