- name: Copy application servicefile
  ansible.builtin.copy:
    src: "{{ app_name }}.service"
    dest: /etc/systemd/system/{{ app_name }}.service

- name: Enable and start app service
  ansible.builtin.systemd_service:
    name: "{{ app_name }}"
    enabled: true
    deamon_reload: true
    state: started